---
- name: Ubuntu Linux Distribution
  hosts: 10.200.0.7
  gather_facts: yes
  become: true
  tasks:
  - name: Distribution
    debug: msg="{{ ansible_distribution }}"

  - name: Distribution version
    debug: msg="{{ ansible_distribution_version}}"

  - name: Distribution major version
    debug: msg="{{ ansible_distribution_major_version }}"
    
- name: Create a file in the home directory if it doesn't exist
  hosts: 10.200.0.7
  tasks:
  - name: Create a file in the home directory
    shell: echo "Hey guys!" > /home/ansible/hello.txt
    args:
      creates: "/home/ansible/hello.txt"

- name: Create a file in the home directory if it doesn't exist
  hosts: 10.200.0.7
  tasks:
  - name: Create a file in the home directory
    shell: | 
      echo "Running Ansible Cisco Interface Description!" > /home/ansible/cisco.txt
      cd /opt/u000/ondemadproject
      ansible-playbook -i /opt/u000/inventory/ncr_bg_lab_inventory2 show_interface_description_cisco2.yml -vvv
    args:
      creates: "/home/ansible/cisco.txt"
